export enum OrderType {
  DINE_IN = 'DINE_IN',
  TAKEAWAY = 'TAKEAWAY',
  DELIVERY = 'DELIVERY',
  CURBSIDE = 'CURBSIDE',
  DRIVE_THRU = 'DRIVE_THRU',
  AGGREGATOR = 'AGGREGATOR',
  CATERING = 'CATERING',
  PRE_ORDER = 'PRE_ORDER',
}

export enum OrderChannel {
  POS = 'POS',
  QR = 'QR',
  KIOSK = 'KIOSK',
  MOBILE_APP = 'MOBILE_APP',
  CALL_CENTER = 'CALL_CENTER',
  AGGREGATOR = 'AGGREGATOR',
}

export enum OrderStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  PREPARING = 'PREPARING',
  READY = 'READY',
  SERVED = 'SERVED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum OrderItemStatus {
  PENDING = 'PENDING',
  PREPARING = 'PREPARING',
  READY = 'READY',
  SERVED = 'SERVED',
  CANCELLED = 'CANCELLED',
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  ITEM = 'ITEM',
  COMP = 'COMP',
}

export enum PaymentMethod {
  CASH = 'CASH',
  CARD = 'CARD',
  UPI = 'UPI',
  DIGITAL_WALLET = 'DIGITAL_WALLET',
  NET_BANKING = 'NET_BANKING',
  BNPL = 'BNPL',
  GIFT_CARD = 'GIFT_CARD',
  STORE_CREDIT = 'STORE_CREDIT',
  LOYALTY_POINTS = 'LOYALTY_POINTS',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  VOIDED = 'VOIDED',
}
