export enum Permission {
  // Tenant permissions
  TENANT_CREATE = 'TENANT_CREATE',
  TENANT_READ = 'TENANT_READ',
  TENANT_UPDATE = 'TENANT_UPDATE',
  TENANT_DELETE = 'TENANT_DELETE',

  // Site permissions
  SITE_CREATE = 'SITE_CREATE',
  SITE_READ = 'SITE_READ',
  SITE_UPDATE = 'SITE_UPDATE',
  SITE_DELETE = 'SITE_DELETE',

  // User permissions
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  // Menu permissions
  MENU_CREATE = 'MENU_CREATE',
  MENU_READ = 'MENU_READ',
  MENU_UPDATE = 'MENU_UPDATE',
  MENU_DELETE = 'MENU_DELETE',

  // Order permissions
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_READ = 'ORDER_READ',
  ORDER_UPDATE = 'ORDER_UPDATE',
  ORDER_DELETE = 'ORDER_DELETE',

  // Staff management
  STAFF_MANAGE = 'STAFF_MANAGE',
  STAFF_SCHEDULE = 'STAFF_SCHEDULE',

  // Maintenance
  MAINTENANCE_MANAGE = 'MAINTENANCE_MANAGE',
  MAINTENANCE_VIEW = 'MAINTENANCE_VIEW',

  // Quality compliance
  QUALITY_AUDIT = 'QUALITY_AUDIT',
  QUALITY_VIEW = 'QUALITY_VIEW',

  // Digital signage
  SIGNAGE_MANAGE = 'SIGNAGE_MANAGE',
  SIGNAGE_VIEW = 'SIGNAGE_VIEW',

  // Customer surveys
  SURVEY_CREATE = 'SURVEY_CREATE',
  SURVEY_VIEW = 'SURVEY_VIEW',

  // System admin
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
}
