export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  BRAND_MANAGER = 'BRAND_MANAGER',
  SITE_LEAD = 'SITE_LEAD',
  KITCHEN_STAFF = 'KITCHEN_STAFF',
  FOH = 'FOH',
  MAINTENANCE_TECH = 'MAINTENANCE_TECH',
  QUALITY_AUDITOR = 'QUALITY_AUDITOR',
  HR_ADMIN = 'HR_ADMIN',
  MARKETING_ADMIN = 'MARKETING_ADMIN',
  CUSTOMER = 'CUSTOMER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  INVITED = 'INVITED',
  SUSPENDED = 'SUSPENDED',
}
